# See the docs at https://github.com/geocoder-php/BazingaGeocoderBundle
bazinga_geocoder:
    # The local IP (127.0.0.1) will be replaced by the fake_ip
    # see https://github.com/geocoder-php/BazingaGeocoderBundle/blob/5.0.0/Resources/doc/index.md#fake-local-ip
    fake_ip: 123.123.123.123
    providers:
        google_maps:
            locale:               fr
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
            options:
                # httplug_client: '@httplug.client' # When using HTTPlugBundle
                # region: 'Sweden'
                api_key: 'AIzaSyBgah9u8A21CdN6O_fN80Op-4zcLJ0EwXk'
            # region:               null
            # use_ssl:              true
            # api_key:
        # openstreetmap:
        #     locale:               fr