sonata_admin:
    security:
        handler: custom.sonata.security.handler.role # sonata.admin.security.handler.role
        information:
            LIST: LIST
            CREATE: CREATE
            EDIT: EDIT
            DELETE: DELETE
            EXPORT: EXPORT

    options:
        confirm_exit: false
    templates:
        # default global templates
        layout:  "bundles/SonataAdminBundle/layout.html.twig"
        edit:    "admin/core_custom/base_edit.html.twig"
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: gogo.block.recent_elements, settings: { title: 'Dernières validation collaboratives', filterStatus: 2, class: box-success}}
            - { position: right, type: gogo.block.recent_elements, settings: { title: 'Derniers refus collaboratifs', filterStatus: -3 , class: box-danger}}
            - { position: top, class: col-md-12, type: sonata.block.service.monitoring}
            - { position: top, class: col-md-12, type: sonata.block.service.charts}
        groups:
            Contenus:
                icon: <i class='fa fa-file-text'></i>
            data:
                label: "Données"
                icon: <i class='fa fa-database'></i>
            custom:
                label: Personnalisation
                icon: <i class='fa fa-paint-brush'></i>
            data_model:
                label: Modèle de donnée
                icon: <i class='fa fa-database'></i>
            emailing:
                label: Mails / Newsletter
                icon: <i class='fa fa-envelope'></i>
            other_config:
                label: Autre Configuration
                icon: <i class='fa fa-cogs'></i>
            sonata_user:
                label: Utilisateurs
                icon: <i class='fa fa-users'></i>

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        # enable the SonataAdminBundle block
        sonata.block.service.monitoring:
        sonata.block.service.charts:
        gogo.block.recent_elements:
            contexts: [admin]