version: '3'

services:

  gogocarto:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    depends_on:
      - mongo
    container_name: gogocarto
    volumes:
      - ./app:/var/www/app:cached
      - ./bin:/var/www/bin:cached
      - ./src:/var/www/src:cached
      - ./var:/var/www/var:cached
      - ./web:/var/www/web:cached
      - /var/www/var/cache
      - /var/www/var/logs
      - /var/www/var/sessions
    ports:
      - "80:80"
    links:
      - mongo:mongo
    tty: true

  mongo:
    image: shikhir/alpine-mongodb
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    tty: true

volumes:
  mongo: {}
