biopen_api_ui:
    path: /
    defaults: { _controller: BiopenCoreBundle:API:apiUi }

biopen_api_manifest:
    path:     /manifest.{_format}
    defaults: { _controller: BiopenCoreBundle:API:getManifest, _format: json }
    requirements:
        methods: GET
        _format: json

biopen_api_project_info:
    path:     /project-info.json
    defaults: { _controller: BiopenCoreBundle:API:getProjectInfo }
    requirements:
        methods: GET

biopen_api_configuration:
    path:     /configuration.json
    defaults: { _controller: BiopenCoreBundle:API:getConfiguration }
    requirements:
        methods: GET

biopen_api_log_hide:
    path:     /log/{id}/hide
    defaults: { _controller: BiopenCoreBundle:API:hideLog }
    requirements:
        methods: POST
