services:

    # --------- CONTENUS -----------

    admin.wrapper:
        class: Biopen\CoreBundle\Admin\WrapperAdmin
        arguments: [~, Biopen\CoreBundle\Document\Wrapper, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Bandeaux de la page d'accueil }

    admin.partner:
        class: Biopen\CoreBundle\Admin\PartnerAdmin
        arguments: [~, Biopen\CoreBundle\Document\Partner, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Partenaires }

    admin.about:
        class: Biopen\CoreBundle\Admin\AboutAdmin
        arguments: [~, Biopen\CoreBundle\Document\About, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenus", label: Popups type "A propos" }    
    

    # --------- CONFIGURATION -----------
    
    admin.config:
        class: Biopen\CoreBundle\Admin\ConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: custom, label: Configuration Générale }    

    admin.style_config:
        class: Biopen\CoreBundle\Admin\ConfigurationStyleAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: custom, label: Style / Couleurs / Icones }

    admin.home_config:
        class: Biopen\CoreBundle\Admin\ConfigurationHomeAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: custom, label: Page d'Accueil }

    admin.map_config:
        class: Biopen\CoreBundle\Admin\ConfigurationMapAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: custom, label: La Carte }

    admin.tile_layer:
        class: Biopen\CoreBundle\Admin\TileLayerAdmin
        arguments: [~, Biopen\CoreBundle\Document\TileLayer, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: custom, label: Fonds de Carte }
    
    admin.contributions_config:
        class: Biopen\CoreBundle\Admin\ConfigurationContributionsAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: data_model, label: Qui peut Contribuer? }    

    admin.form_config:
        class: Biopen\CoreBundle\Admin\ConfigurationFormAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: data_model, label: Formulaire }

    admin.category:
        class: Biopen\GeoDirectoryBundle\Admin\CategoryAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Category, 'BiopenGeoDirectoryBundle:Admin/CategoryAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: data_model, label: Catégories }     

    admin.map_element_form_config:
        class: Biopen\CoreBundle\Admin\ConfigurationInfoBarAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: data_model, label: Fiche Détail }    

    admin.mail_config:
        class: Biopen\CoreBundle\Admin\ConfigurationMailAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: emailing, label: Mails / Newsletter }

    admin.login_config:
        class: Biopen\CoreBundle\Admin\ConfigurationUserAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: other_config, label: Utilisateurs / Connexion }    

    admin.api_config:
        class: Biopen\CoreBundle\Admin\ConfigurationAPIAdmin
        arguments: [~, Biopen\CoreBundle\Document\Configuration, 'BiopenCoreBundle:ConfigurationAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: other_config, label: APIs }

    admin.webhook:
        class: Biopen\GeoDirectoryBundle\Admin\WebhookAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Webhook, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: other_config, label: Webhooks }
    
    
    # --------- HIDDEN -----------

    admin.parter_image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\PartnerImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }   

    admin.conf_image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\ConfImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }     

    admin.image:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\CoreBundle\Document\EmbeddedImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" } 

    admin.feature_config:
        class: Biopen\CoreBundle\Admin\FeatureConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\FeatureConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.interaction_config:
        class: Biopen\CoreBundle\Admin\InteractionConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\InteractionConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.automated_mail_config:
        class: Biopen\CoreBundle\Admin\AutomatedMailConfigurationAdmin
        arguments: [~, Biopen\CoreBundle\Document\AutomatedMailConfiguration, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }


    