biopen_mail_draft_automated:
    path: /test-emails/automated/{mailType}
    defaults: { _controller: App\Controller\MailTestController::draftAutomatedAction }

biopen_mail_send_test_automated:
    path: /test-emails/automated/send/{mailType}
    defaults: { _controller: App\Controller\MailTestController::sentTestAutomatedAction }

biopen_core_help:
    path: /help
    defaults: { _controller: App\Controller\CoreController::helpAction }

# BULK ACTIONS
biopen_bulk_actions_index:
    path: /admin/bulkActions/index
    defaults: { _controller: App\Controller\Admin\BulkActions\BulkCoreController::indexAction }

biopen_bulk_actions_delete_element_reported:
    path: /admin/bulkActions/deleteElementReportedAsNoMoreExisting
    defaults: { _controller: App\Controller\Admin\BulkActions\ModerationActionsController::deleteElementReportedAsNoMoreExistingAction }

biopen_bulk_actions_update_gamification:
    path: /admin/bulkActions/updateGamification
    defaults: { _controller: App\Controller\Admin\BulkActions\DataUpdateActionsController::updateGamificationAction }

biopen_bulk_actions_detect_duplicates:
    path: /admin/bulkActions/detectDuplicates
    defaults: { _controller: App\Controller\Admin\BulkActions\DuplicatesActionsController::detectDuplicatesAction }

# DUPLICATES
biopen_duplicates_index:
    path: /duplicates
    defaults: { _controller: App\Controller\DuplicatesController::indexAction }

biopen_mark_as_non_duplicate:
    path: /duplicates/mark-as-non-duplicate
    defaults: { _controller: App\Controller\DuplicatesController::markAsNonDuplicateAction }
    requirements:
        methods: POST

# IMPORT
biopen_element_import_available_options:
    path:     /admin/import/available-options
    defaults: { _controller: App\Controller\ImportController::availableOptionsAction }

biopen_import_state:
    path:     /admin/import/{id}/state
    defaults: { _controller: App\Controller\ImportController::currStateAction }
    requirements:
        methods: GET

biopen_element_generate:
    path:     /generate/{nombre}/{generateVotes}
    controller: App\Controller\ImportController::generateRandomAction
    defaults:
        nombre: '1'
        generateVotes: '0'