saas:
    resource: "@BiopenSaasBundle/Resources/config/routing.yml"
    prefix:   /

biopen_core:
    resource: "@BiopenCoreBundle/Resources/config/routing.yml"
    prefix:   /

biopen_geo_directory:
    resource: "@BiopenGeoDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin



hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   oauth/login

facebook_login:
    path: /login/check-facebook

gplus_login:
    path: /login/check-google

communs_login:
    path: /login/check-les-communs

yahoo_login:
    path: /login/check-yahoo

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

other:
    path: /{arg1}/{arg2}/{arg3}/{arg4}/{arg5}/{arg6}
    defaults: { _controller: BiopenCoreBundle:Core:home, arg1: '', arg2: '', arg3: '', arg4: '', arg5: '', arg6: '' }

