services:
    sonata.block.service.monitoring:
        class: Biopen\GeoDirectoryBundle\Block\MonitoringElementsBlockService
        public: true
        arguments: [ "@templating", "@doctrine.odm.mongodb.document_manager" ]
        tags:
            - { name: sonata.block }

    sonata.block.service.charts:
        class: Biopen\GeoDirectoryBundle\Block\ChartBlockService
        public: true
        arguments: [ "@templating", "@doctrine.odm.mongodb.document_manager", "@biopen.config_service" ]
        tags:
            - { name: sonata.block }

    biopen.block.recent_elements:
        class: Biopen\GeoDirectoryBundle\Block\RecentElementsBlockService
        public: true
        arguments: [ "@templating", "@doctrine.odm.mongodb.document_manager", "@sonata.admin.pool" ]
        tags:
            - { name: sonata.block }
