monolog:
    channels: ['commands']
    handlers:
        # main:
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        command:
            type: stream
            path: "%kernel.logs_dir%/commands.log"
            level: debug
            channels: ['commands']
        console:
            type:   console
            process_psr_3_messages: false
            bubble: false
            channels: ['!event', '!doctrine']
