# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['sebastian.castro@protonmail.com']
    disable_delivery:  true
