services:
    gogo.form.element:
        class: App\Form\ElementType
        public: true
        arguments: [ "@doctrine.odm.mongodb.document_manager" ]
        tags:
            - { name: form.type }

    gogo.element_vote_service:
       public: true
       class: App\Services\ElementVoteService
       arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage", "@gogo.config_service", "@gogo.element_pending_service" ]

    gogo.element_action_service:
       class: App\Services\ElementActionService
       public: true
       arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage", "@gogo.mail_service", "@gogo.element_pending_service", "@gogo.user_interaction_service" ]

    gogo.element_pending_service:
       class: App\Services\ElementPendingService
       public: true
       arguments: [ "@doctrine.odm.mongodb.document_manager", "@gogo.mail_service", "@gogo.user_interaction_service" ]

    gogo.element_form_service:
       class: App\Services\ElementFormService
       public: true
       arguments: [ "@gogo.element_action_service" ]

    gogo.element_duplicates_service:
       public: true
       class: App\Services\ElementDuplicatesService
       arguments: [ "@doctrine.odm.mongodb.document_manager" ]

    gogo.random_creation_service:
       class: App\Services\RandomCreationService
       public: true
       arguments: [ "@doctrine.odm.mongodb.document_manager" ]

    gogo.user_interaction_service:
       class: App\Services\UserInteractionService
       public: true
       arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage" ]

    gogo.webhook_service:
      class: App\Services\WebhookService
      public: true
      arguments: [ "@doctrine.odm.mongodb.document_manager", "@router", "@security.token_storage", "%base_url%", "%base_path%" ]

    gogo.taxonomy_json_generator:
        class: App\EventListener\TaxonomyJsonGenerator
        public: true
        arguments: [ '@jms_serializer' ]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postFlush }
            - { name: doctrine_mongodb.odm.event_listener, event: preFlush }
            - { name: doctrine_mongodb.odm.event_listener, event: postUpdate }

    gogo.element_json_generator:
        class: App\EventListener\ElementJsonGenerator
        public: true
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: preFlush }

    gogo.db_integrity:
        class: App\EventListener\DatabaseIntegrityWatcher
        public: true
        arguments: ["@gogo.async"]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: preRemove }
            - { name: doctrine_mongodb.odm.event_listener, event: preFlush }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }

    gogo.element_import:
       class: App\Services\ElementImportService
       public: true
       arguments:
          - "@doctrine.odm.mongodb.document_manager"
          - '@gogo.element_import_one'
          - "@gogo.element_import_mapping"
          - "@gogo.taxonomy_json_generator"

    gogo.element_import_one:
       class: App\Services\ElementImportOneService
       public: true
       arguments:
          - "@doctrine.odm.mongodb.document_manager"
          - '@bazinga_geocoder.geocoder'
          - "@gogo.user_interaction_service"

    gogo.element_import_mapping:
       class: App\Services\ElementImportMappingService
       public: true
       arguments:
          - "@doctrine.odm.mongodb.document_manager"

    gogo.gogocartojs_service:
       class: App\Services\GoGoCartoJsService
       public: true
       arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage", "@router", "@session", "%base_protocol%" ]
