version: '3'

services:

  gogocarto:
    build: server
    container_name: gogocarto
    volumes:
      - ..:/var/www
      - /var/www/var/cache
      - /var/www/var/logs
      - /var/www/var/sessions

    ports:
      - "80:80"
    links:
      - mongo:mongo

  mongo:
    image: shikhir/alpine-mongodb
    container_name: mongo
    volumes:
      - ./.mongo:/data/db
    ports:
      - "27017:27017"