services:
    admin.elements:
        class: Biopen\GeoDirectoryBundle\Admin\Element\ElementAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Element, 'BiopenGeoDirectoryBundle:Admin/ElementAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "data", label: Éléments }

    admin.imports:
        class: Biopen\GeoDirectoryBundle\Admin\ImportAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Import, 'BiopenGeoDirectoryBundle:Admin/ImportAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "data", label: Import }

    admin.imports_dynamiques:
        class: Biopen\GeoDirectoryBundle\Admin\ImportAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\ImportDynamic, 'BiopenGeoDirectoryBundle:Admin/ImportAdmin' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "data", label: Import dynamique }




    admin.element_image_hidden:
        class: Biopen\CoreBundle\Admin\ImageAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\ElementImage, '' ]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.option_hidden:
        class: Biopen\GeoDirectoryBundle\Admin\OptionAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Option, 'BiopenGeoDirectoryBundle:Admin/OptionAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.option.lite_hidden:
        class: Biopen\GeoDirectoryBundle\Admin\OptionLiteAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Option, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }

    admin.categories:
        class: Biopen\GeoDirectoryBundle\Admin\CategoryAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Category, 'BiopenGeoDirectoryBundle:Admin/CategoryAdmin']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: data_model, label: Catégories }

    admin.categories.lite_hidden:
        class: Biopen\GeoDirectoryBundle\Admin\CategoryLiteAdmin
        arguments: [~, Biopen\GeoDirectoryBundle\Document\Category, '']
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Hide" }


