services:
  biopen_user.gamification:
    class: Application\Sonata\UserBundle\Services\GamificationService
    arguments: [ "@doctrine.odm.mongoDB.document_manager" ]

  biopen_user.registration.form.type:
    class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
    arguments: [ %fos_user.model.user.class% ]
    tags:
      - { name: "form.type", alias: "biopen_user_registration"}

  biopen.registration.form.handler:
    class: Application\Sonata\UserBundle\Form\Handler\RegistrationFormHandler
    scope: "request"
    arguments:
      - "@request_stack"
      - "@fos_user.user_manager"
      - "@fos_user.mailer"
      - "@fos_user.util.token_generator"
      - "@bazinga_geocoder.geocoder"