services:




  biopen.config_service:
    class: App\Services\ConfigurationService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage" ]

  biopen.mail_service:
    class: App\Services\MailService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@mailer", "@router", "@twig", "%base_url%", "%base_path%", "%use_as_saas%", "%mailer_user%", "%env(instance_name)%" ]

  biopen.newsletter_service:
    class: App\Services\NewsletterService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@biopen.mail_service" ]

  biopen.upload_directory_namer:
    class: App\Services\UploadDirectoryNamer
    public: true
    arguments: []

  biopen.image_resizer:
    class: App\EventListener\ImageResizer
    public: true
    arguments:
        - '%env(IMAGE_RESIZE_WIDTH)%'
    tags:
        - { name: doctrine_mongodb.odm.event_listener, event: postPersist }

  biopen.config_listener:
    class: App\EventListener\ConfigurationListener
    public: true
    tags:
        - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
    arguments: [ "@biopen.async" ]

  biopen.async.factory:
    class: App\Services\AsyncServiceFactory
    public: true
    arguments:
        - '@filesystem'
        - '%kernel.root_dir%'
        - 'bin/console'
        - null

  biopen.async:
    class: App\Services\AsyncService
    public: true
    factory: 'biopen.async.factory:createAsyncService'
