services:




  gogo.config_service:
    class: App\Services\ConfigurationService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@security.token_storage" ]

  gogo.mail_service:
    class: App\Services\MailService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@mailer", "@router", "@twig", "%base_url%", "%base_path%", "%use_as_saas%", "%from_email%", "%env(instance_name)%" ]

  gogo.newsletter_service:
    class: App\Services\NewsletterService
    public: true
    arguments: [ "@doctrine.odm.mongodb.document_manager", "@gogo.mail_service" ]




